import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import Provider from '@/components/providers/nextui-provider';
import ProviderClerk from '@/components/providers/clerk-provider';
import Header from '@/components/header';

// const geistSans = localFont({
//     src: './fonts/GeistVF.woff',
//     variable: '--font-geist-sans',
//     weight: '100 900',
// });
// const geistMono = localFont({
//     src: './fonts/GeistMonoVF.woff',
//     variable: '--font-geist-mono',
//     weight: '100 900',
// });

const NunitoFont = Nunito({
    subsets: ['cyrillic'],
});

export const metadata: Metadata = {
    title: 'Storystore',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ProviderClerk>
            <html lang="en">
                <body className={`${NunitoFont.className} antialiased`}>
                    <Provider>
                        <Header />
                        {children}
                    </Provider>
                </body>
            </html>
        </ProviderClerk>
    );
}
